// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh8U-Vf9vwC0U3zurU2L8cQOMgzTqWyiQ',
    appId: '1:428933250476:web:3239d30cd4fdc8581c4e09',
    messagingSenderId: '428933250476',
    projectId: 'flutter-demo-170b8',
    authDomain: 'flutter-demo-170b8.firebaseapp.com',
    storageBucket: 'flutter-demo-170b8.firebasestorage.app',
    measurementId: 'G-PTLBL6QPM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5BnLE4-XM8cWDysJHgkAd-yfW3x9868',
    appId: '1:428933250476:android:ef565871e5bcee2d1c4e09',
    messagingSenderId: '428933250476',
    projectId: 'flutter-demo-170b8',
    storageBucket: 'flutter-demo-170b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsG3tIN17CQJ4qHCCF6K5HHdo3_eDiRQ',
    appId: '1:428933250476:ios:6d5bd8456a78ed221c4e09',
    messagingSenderId: '428933250476',
    projectId: 'flutter-demo-170b8',
    storageBucket: 'flutter-demo-170b8.firebasestorage.app',
    iosClientId: '428933250476-r6bd28t4ftjefcug7pomf0g047pfs207.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiBaseCulturalHeritagePreservationPlatform',
  );

}